/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author LuisE
 */
public class PanelRolUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelRolUsuarios
     */
    public PanelRolUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnRolRegistrar = new javax.swing.JButton();
        btnRolEditar = new javax.swing.JButton();
        btnRolBuscar = new javax.swing.JButton();
        btnRolEliminar = new javax.swing.JButton();
        btnRolNuevo = new javax.swing.JButton();
        btnRolSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRolUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtRolNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtRolObservaciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRol = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 255, 204));

        btnRolRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/AgregarUsuario.png"))); // NOI18N
        btnRolRegistrar.setText("Registrar");

        btnRolEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/EditarUsuario.png"))); // NOI18N
        btnRolEditar.setText("Editar");

        btnRolBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BuscarUsuario.png"))); // NOI18N
        btnRolBuscar.setText("Buscar");

        btnRolEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/EliminarUsuario.png"))); // NOI18N
        btnRolEliminar.setText("Eliminar");

        btnRolNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NuevoArchivo.png"))); // NOI18N
        btnRolNuevo.setText("Nuevo");
        btnRolNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolNuevoActionPerformed(evt);
            }
        });

        btnRolSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Salir.png"))); // NOI18N
        btnRolSalir.setText("Salir");

        jLabel1.setText("ID Usuario");

        jLabel2.setText("Nombre");

        TxtRolNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRolNombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Observaciones");

        TablaRol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaRol);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnRolRegistrar)
                        .addGap(12, 12, 12)
                        .addComponent(btnRolEditar)
                        .addGap(13, 13, 13)
                        .addComponent(btnRolBuscar)
                        .addGap(20, 20, 20)
                        .addComponent(btnRolEliminar)
                        .addGap(78, 78, 78)
                        .addComponent(btnRolNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRolSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TxtRolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(TxtRolObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRolRegistrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRolEditar)
                            .addComponent(btnRolBuscar)
                            .addComponent(btnRolEliminar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRolSalir)
                                .addComponent(btnRolNuevo)))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(TxtRolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TxtRolObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRolNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRolNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRolNombreActionPerformed

    private void btnRolNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRolNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaRol;
    public javax.swing.JTextField TxtRolNombre;
    public javax.swing.JTextField TxtRolObservaciones;
    public javax.swing.JButton btnRolBuscar;
    public javax.swing.JButton btnRolEditar;
    public javax.swing.JButton btnRolEliminar;
    public javax.swing.JButton btnRolNuevo;
    public javax.swing.JButton btnRolRegistrar;
    public javax.swing.JButton btnRolSalir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtRolUsuario;
    // End of variables declaration//GEN-END:variables
}
